
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 10;
  public static final int PIPE = 18;
  public static final int M_CHAR = 21;
  public static final int CM = 12;
  public static final int S = 7;
  public static final int RO = 16;
  public static final int COL = 20;
  public static final int PART_WD = 19;
  public static final int RC = 15;
  public static final int EOF = 0;
  public static final int TOK3 = 6;
  public static final int TOK2 = 5;
  public static final int DIVIDER = 8;
  public static final int TOK1 = 4;
  public static final int error = 1;
  public static final int ARROW = 14;
  public static final int EQ = 11;
  public static final int MEASURE = 13;
  public static final int BO = 9;
  public static final int UINT = 3;
  public static final int QSTRING = 2;
  public static final int PRINT_WD = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "QSTRING",
  "UINT",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "DIVIDER",
  "BO",
  "BC",
  "EQ",
  "CM",
  "MEASURE",
  "ARROW",
  "RC",
  "RO",
  "PRINT_WD",
  "PIPE",
  "PART_WD",
  "COL",
  "M_CHAR"
  };
}

