
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 5;
  public static final int TOK1 = 4;
  public static final int EUROWORD = 7;
  public static final int INT = 13;
  public static final int QSTRING = 12;
  public static final int CM = 8;
  public static final int S = 3;
  public static final int EOF = 0;
  public static final int SEP = 11;
  public static final int REAL = 14;
  public static final int PERC = 6;
  public static final int error = 1;
  public static final int TOK3 = 10;
  public static final int TOK2 = 9;
  public static final int CONST = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONST",
  "S",
  "TOK1",
  "MINUS",
  "PERC",
  "EUROWORD",
  "CM",
  "TOK2",
  "TOK3",
  "SEP",
  "QSTRING",
  "INT",
  "REAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[5]=new String("MINUS");
		TT[4]=new String("TOK1");
		TT[7]=new String("EUROWORD");
		TT[13]=new String("INT");
		TT[12]=new String("QSTRING");
		TT[8]=new String("CM");
		TT[3]=new String("S");
		TT[0]=new String("EOF");
		TT[11]=new String("SEP");
		TT[14]=new String("REAL");
		TT[6]=new String("PERC");
		TT[1]=new String("error");
		TT[10]=new String("TOK3");
		TT[9]=new String("TOK2");
		TT[2]=new String("CONST");
	}
public String getTT(int i){return TT[i];}
}

