
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 8;
  public static final int COMPARE_WD = 20;
  public static final int PLUS = 16;
  public static final int CM = 11;
  public static final int STAR = 18;
  public static final int S = 5;
  public static final int RO = 14;
  public static final int COL = 12;
  public static final int ID = 10;
  public static final int RC = 15;
  public static final int EOF = 0;
  public static final int DIV = 19;
  public static final int TOK2 = 3;
  public static final int DIVIDER = 9;
  public static final int MINUS = 17;
  public static final int TOK1 = 2;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int END_WD = 22;
  public static final int BO = 6;
  public static final int UINT = 4;
  public static final int PRINT_WD = 7;
  public static final int WITH_WD = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOK1",
  "TOK2",
  "UINT",
  "S",
  "BO",
  "PRINT_WD",
  "BC",
  "DIVIDER",
  "ID",
  "CM",
  "COL",
  "EQ",
  "RO",
  "RC",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "COMPARE_WD",
  "WITH_WD",
  "END_WD"
  };
}

