
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CM = 13;
  public static final int S = 5;
  public static final int NUM_BETWEEN = 19;
  public static final int USERCODE = 10;
  public static final int COL = 9;
  public static final int ID = 8;
  public static final int USERNUMBER = 11;
  public static final int EOF = 0;
  public static final int MIN_WD = 16;
  public static final int TOK2 = 4;
  public static final int DIVIDER = 6;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int DOT = 12;
  public static final int UINT = 2;
  public static final int QSTRING = 15;
  public static final int ARR_WD = 17;
  public static final int REAL = 7;
  public static final int AUCTION_WD = 14;
  public static final int EURO_WD = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UINT",
  "TOK1",
  "TOK2",
  "S",
  "DIVIDER",
  "REAL",
  "ID",
  "COL",
  "USERCODE",
  "USERNUMBER",
  "DOT",
  "CM",
  "AUCTION_WD",
  "QSTRING",
  "MIN_WD",
  "ARR_WD",
  "EURO_WD",
  "NUM_BETWEEN"
  };
}

